Revert to breath sof-setup-audio

diff --git a/postinstall-scripts/sof-setup-audio b/postinstall-scripts/sof-setup-audio
--- a/postinstall-scripts/sof-setup-audio
+++ b/postinstall-scripts/sof-setup-audio
@@ -1,80 +1,185 @@
-#!/usr/bin/env python3
+#!/bin/bash
+#
 
-import os
-import argparse
-from functions import *
+set -e
 
+echo "Installing Audio..."
 
-def process_args():
-    print("\033[95m" + "Processing args" + "\033[0m")
-    parser = argparse.ArgumentParser()
-    parser.add_argument('-v', '--version', default="v2.2.x", help="Sof version to install, default: v2.2.x")
-    parser.add_argument("--no-pulseaudio", "--no-pa", action="store_true", dest="no_pa", default=False,
-                        help="Only install alsa")
-    parser.add_argument('-p', '--local-path', dest="local_path",
-                        help="Local path for config files to use instead of downloading from github.")
-    return parser.parse_args()
+# With SOF, configuration becomes much easier
+# Everything is pretty much universal, like HD-Audio
+# The kernel ignores modules extraneous modules,
+# so there shouldn't be any problems loading all of them
+SND_MODULES="snd_soc_max98357a snd_soc_da7219 snd_soc_rt5682 snd_soc_rt1015 snd_soc_rt1011" 
 
+if [[ -v ONLY_ALSA ]]; then
 
-def download_files() -> None:
-    print("\033[94m" + "Downloading files from github" + "\033[0m")
-    print("Removing old files")
-    rmdir("/tmp/eupnea-audio")
-    rmdir("/tmp/sof-audio")
-    print("Downloading config files from github")
-    bash("git clone --depth 1 https://github.com/eupnea-linux/eupnea /tmp/eupnea-audio")
-    print("Downloading sof audio from github")
-    bash("git clone --depth 1 https://github.com/thesofproject/sof-bin /tmp/sof-audio")
+    # Remove PulseAudio
+    sudo apt install -y apulse alsa-* rsync
+    sudo apt install -y firmware-sof-signed || sudo apt-get -o Dpkg::Options::="--force-overwrite" install firmware-sof-signed
 
+    # On newer GNOME installs, Pipewire is a dependency of GNOME.
+    # We can't remove it, but we can mask (completely disable) the systemd service
+    {
+        systemctl --user mask pipewire.socket
+        systemctl --user mask pipewire.service
+        systemctl --user mask pulseaudio.socket
+        systemctl --user mask pulseaudio.service
+    } || true
 
-def install_pa(path: str, sof_version: str) -> None:
-    print("\033[95m" + "Removing old files" + "\033[0m")
-    if sof_version is None:
-        sof_version = "v2.2.x"
-    rmfile("/etc/systemd/system/alsa-reload.service")
-    rmfile("/etc/pulse/default.pa")
-    rmfile("/etc/modprobe.d/alsa-breath.conf")
-    rmfile("/etc/asound.conf")
+    # Enable Dmix (multiple app audio output) and software master volume control
+sudo tee /etc/asound.conf <<EOF
+pcm.!default {
+    type plug
+    slave.pcm "softvol"
+}
 
-    if path == "":
-        # remove all old sof folders + files
-        bash("rm -rf /lib/firmware/intel/sof*")
-        print("\033[95m" + "Installing sof-audio" + "\033[0m")
-        cpdir(f"/tmp/sof-audio/{sof_version}/sof", "/lib/firmware/intel/sof")
-        cpdir(f"/tmp/sof-audio/{sof_version}/sof-tplg", "/lib/firmware/intel/sof-tplg")
-        # remove old sof scripts
-        for file in Path("/usr/local/bin/").glob("sof*"):
-            if not str(file).find("sof-setup-audio") == -1:
-                continue
-            else:
-                rmfile(file.absolute().as_posix())
-        for script in os.listdir("/tmp/sof-audio/" + sof_version + "/tools-" + sof_version[:sof_version.rfind(".")]):
-            cpfile(f'/tmp/sof-audio/{sof_version}/tools-{sof_version[:sof_version.rfind(".")]}/{script}',
-                   "/usr/local/bin/")
-        # set path to temp if no path is given
-        path = "/tmp/eupnea-audio/configs/audio/"
-    print("Installing audio services")
-    cpfile(f"{path}alsa-reload.service", "/etc/systemd/system/alsa-reload.service")
-    bash("systemctl enable alsa-reload")
-    print("Copying pa config")
-    cpfile(f"{path}default.pa", "/etc/pulse/default.pa")
-    print("Blacklising old drivers")
-    cpfile(f"{path}alsa-breath.conf", "/etc/modprobe.d/alsa-breath.conf")
-    print("Copying asound.conf")
-    cpfile(f"{path}asound.conf", "/etc/asound.conf")
+pcm.softvol {
+    type softvol # Software volume control
+    slave {
+        pcm "dmix"
+    }
+    control {
+        name "Master"
+        card 0
+    }
+}
+EOF
 
+    fi
 
-if __name__ == "__main__":
-    # Elevate script to root
-    if not os.geteuid() == 0:
-        sudo_args = ['sudo', sys.executable] + sys.argv + [os.environ]
-        os.execlpe('sudo', *sudo_args)
-    args = process_args()
-    if not args.local_files:
-        download_files()
-    if not args.no_pa:
-        install_pa(args.local_files, args.version)
-    else:
-        print("\033[93m" + "Error: no-pulseaudio not yet implemented" + "\033[0m")
-        # TODO: Implement alsa only install
-    print("\033[92m" + "Audio installed successfully. Please reboot." + "\033[0m")
+# Add a systemd service to start sound
+# ${SND_MODULES} is expanded to the variable above
+sudo tee /etc/systemd/system/alsa-reload.service <<EOF
+[Unit]
+Description="Reload ALSA and set the correct UCM"
+
+[Service]
+User=root
+WorkingDirectory=/
+ExecStart=/bin/bash -c 'modprobe ${SND_MODULES} && alsactl kill rescan'
+
+[Install]
+WantedBy=multi-user.target
+EOF
+
+# PulseAudio fix
+sudo tee /etc/pulse/default.pa <<EOF
+.fail
+
+    # INPUT/RECORD INTERNAL
+    load-module module-alsa-source device="hw:0,99" tsched=1
+    
+    # INPUT/RECORD EXTERNAL
+    load-module module-alsa-source device="hw:0,1" tsched=1
+    
+    # AUX PORT
+    load-module module-alsa-sink device=hw:0,1 tsched=1
+    
+    # OUTPUT/PLAYBACK
+    load-module module-alsa-sink device="default" tsched=1 
+    
+    # Accept clients
+    load-module module-native-protocol-unix
+
+    # Automatically switch to USB/BT devices
+    .ifexists module-switch-on-connect.so
+    load-module module-switch-on-connect
+    .endif
+
+    # Automatically load driver modules for Bluetooth hardware
+    .ifexists module-bluetooth-policy.so
+    load-module module-bluetooth-policy
+    .endif
+
+    .ifexists module-bluetooth-discover.so
+    load-module module-bluetooth-discover
+    .endif
+
+.nofail
+EOF
+
+# Refresh systemd
+sudo systemctl daemon-reload
+
+if [[ -v ONLY_ALSA ]]; then
+
+    # Replace PulseAudio libraries with Apulse, which makes PulseAudio apps work with ALSA
+    for lib in libpulse-mainloop-glib.so libpulse-simple.so libpulse.so; do
+
+        set +e
+        sudo rm -f /usr/lib/${lib} /usr/lib/${lib}.0 /usr/lib/x86_64-linux-gnu/${lib} /usr/lib/x86_64-linux-gnu/${lib}.0
+        set -e
+
+        sudo ln -s /usr/lib/x86_64-linux-gnu/apulse/${lib}   "/usr/lib/${lib}"
+        sudo ln -s /usr/lib/x86_64-linux-gnu/apulse/${lib}.0 "/usr/lib/${lib}.0"
+        sudo ln -s /usr/lib/x86_64-linux-gnu/apulse/${lib}   "/usr/lib/x86_64-linux-gnu/${lib}"
+        sudo ln -s /usr/lib/x86_64-linux-gnu/apulse/${lib}.0 "/usr/lib/x86_64-linux-gnu/${lib}.0"
+
+    done
+
+elif ! command -v pulseaudio &> /dev/null; then
+
+    # In the case that PulseAudio is not installed for whatever reason,
+    # install it and unmask it
+
+    sudo apt install -y pulseaudio pulseaudio-module-bluetooth pulseaudio-utils
+
+fi
+
+sudo systemctl enable alsa-reload
+
+sudo rm -rfv /lib/firmware/intel/sof* # Symlinks can conflict
+cd /tmp
+git clone --depth 1 "https://github.com/thesofproject/sof-bin"
+cd sof-bin/v2.1.x
+sudo rsync -a sof*v2.1.1   /lib/firmware/intel/
+sudo ln -s sof-v2.1.1      /lib/firmware/intel/sof
+sudo ln -s sof-tplg-v2.1.1 /lib/firmware/intel/sof-tplg
+sudo rsync tools-v2.1.1/*  /usr/local/bin
+cd ..; rm -rf sof-bin; cd # Cleanup
+
+# Mask Pipewire
+systemctl --user mask pipewire.{socket,service}
+
+# Unmask PulseAudio
+systemctl --user unmask pulseaudio.{socket,service}
+
+# Enable PulseAudio
+systemctl --user enable pulseaudio.{socket,service}
+
+# SOF doesn't need SST/HDA drivers, especially on Chromebooks where they conflict
+# The rest of this fixes dependency ordering and prevents the infamous
+# "codec #2 probe error, ret: -2" SOF error
+sudo tee /etc/modprobe.d/alsa-breath.conf <<EOF
+blacklist snd_hda_intel
+blacklist snd_soc_skl
+softdep snd_sof_pci_intel_icl pre: snd_hda_codec_hdmi
+softdep snd_sof_pci_intel_cnl pre: snd_hda_codec_hdmi
+softdep snd_sof_pci_intel_apl pre: snd_hda_codec_hdmi
+softdep snd_sof_pci_intel_tgl pre: snd_hda_codec_hdmi
+softdep snd_sof_pci_intel_tng pre: snd_hda_codec_hdmi
+EOF
+
+# Should be the default, but verify that the correct asound.conf is in place
+sudo tee /etc/asound.conf <<EOF
+pcm.!default {
+  type pulse
+  fallback "sysdefault"
+  hint {
+    show on
+    description "Default ALSA Output (currently PulseAudio Sound Server)"
+  }
+}
+
+ctl.!default {
+  type pulse
+  fallback "sysdefault"
+}
+EOF
+
+# Add a five second delay to PulseAudio to let audio devices initialize
+# This is a messy solution
+sudo sed -i '/ExecStart/a ExecStartPre=/usr/bin/sleep 5' /usr/lib/systemd/user/pulseaudio.service
+
+sync
+echo 'SOF enabled successfully! Reboot to enable audio'
