Print all failed distros

diff --git a/.github/workflows/test-builds.yml b/.github/workflows/test-builds.yml
--- a/.github/workflows/test-builds.yml
+++ b/.github/workflows/test-builds.yml
@@ -183,12 +183,16 @@ jobs:
       - name: Evaluating results
         # Check if the results are not empty and fail the whole workflow if they are
         run: |
-          for file in ./results-*/results*.txt
+          for file in ./results-*/*-results.txt
           do 
             if [ "$(cat $file)" != "[]" ]
               then
-                echo "Build test failed for $file"
-                cat $file
-                exit 1
+                echo $file >> ./failed-results.txt
             fi
+          if [ -s ./failed-results.txt ]
+            then
+              echo "Failed to build the following images:"
+                cat ./failed-results.txt
+                exit 1
+          fi
           done
